/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface DataCard {
        "match": MatchResults;
    }
    interface GoldenPlaza {
    }
    interface MadnessModule {
        "enabled": boolean;
    }
    interface PortalBay {
        "anarchy": boolean;
    }
    interface PortalRoom {
    }
    interface TheCitadel {
    }
}
declare global {
    interface HTMLDataCardElement extends Components.DataCard, HTMLStencilElement {
    }
    var HTMLDataCardElement: {
        prototype: HTMLDataCardElement;
        new (): HTMLDataCardElement;
    };
    interface HTMLGoldenPlazaElement extends Components.GoldenPlaza, HTMLStencilElement {
    }
    var HTMLGoldenPlazaElement: {
        prototype: HTMLGoldenPlazaElement;
        new (): HTMLGoldenPlazaElement;
    };
    interface HTMLMadnessModuleElement extends Components.MadnessModule, HTMLStencilElement {
    }
    var HTMLMadnessModuleElement: {
        prototype: HTMLMadnessModuleElement;
        new (): HTMLMadnessModuleElement;
    };
    interface HTMLPortalBayElement extends Components.PortalBay, HTMLStencilElement {
    }
    var HTMLPortalBayElement: {
        prototype: HTMLPortalBayElement;
        new (): HTMLPortalBayElement;
    };
    interface HTMLPortalRoomElement extends Components.PortalRoom, HTMLStencilElement {
    }
    var HTMLPortalRoomElement: {
        prototype: HTMLPortalRoomElement;
        new (): HTMLPortalRoomElement;
    };
    interface HTMLTheCitadelElement extends Components.TheCitadel, HTMLStencilElement {
    }
    var HTMLTheCitadelElement: {
        prototype: HTMLTheCitadelElement;
        new (): HTMLTheCitadelElement;
    };
    interface HTMLElementTagNameMap {
        "data-card": HTMLDataCardElement;
        "golden-plaza": HTMLGoldenPlazaElement;
        "madness-module": HTMLMadnessModuleElement;
        "portal-bay": HTMLPortalBayElement;
        "portal-room": HTMLPortalRoomElement;
        "the-citadel": HTMLTheCitadelElement;
    }
}
declare namespace LocalJSX {
    interface DataCard {
        "match"?: MatchResults;
    }
    interface GoldenPlaza {
    }
    interface MadnessModule {
        "enabled"?: boolean;
    }
    interface PortalBay {
        "anarchy"?: boolean;
    }
    interface PortalRoom {
    }
    interface TheCitadel {
    }
    interface IntrinsicElements {
        "data-card": DataCard;
        "golden-plaza": GoldenPlaza;
        "madness-module": MadnessModule;
        "portal-bay": PortalBay;
        "portal-room": PortalRoom;
        "the-citadel": TheCitadel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "data-card": LocalJSX.DataCard & JSXBase.HTMLAttributes<HTMLDataCardElement>;
            "golden-plaza": LocalJSX.GoldenPlaza & JSXBase.HTMLAttributes<HTMLGoldenPlazaElement>;
            "madness-module": LocalJSX.MadnessModule & JSXBase.HTMLAttributes<HTMLMadnessModuleElement>;
            "portal-bay": LocalJSX.PortalBay & JSXBase.HTMLAttributes<HTMLPortalBayElement>;
            "portal-room": LocalJSX.PortalRoom & JSXBase.HTMLAttributes<HTMLPortalRoomElement>;
            "the-citadel": LocalJSX.TheCitadel & JSXBase.HTMLAttributes<HTMLTheCitadelElement>;
        }
    }
}
